/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class game_Pawn */

#ifndef _Included_game_Pawn
#define _Included_game_Pawn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     game_Pawn
 * Method:    placePawn
 * Signature: (I[[III)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_game_Pawn_placePawn
  (JNIEnv *, jobject, jint, jobjectArray, jint, jint);

/*
 * Class:     game_Pawn
 * Method:    describe
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_game_Pawn_describe
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
